### PR TITLE
add kfp-tekton 0.8 pre-compiled pipelines

### PR DESCRIPTION
**Pull request by Tomcli**
Add kfp-tekton 0.8 pre-compiled pipelines for MLX version control because Kubeflow 1.3.1 will be based on kfp-tekton 0.8 and Kubeflow won't release the next version for a few months.

### CODE REVIEW

**Comment by Tomcli** [comment]
@ckadner I can add the flip-coin, but that example is pre-installed as part of the api-server. So I will still exclude it in the bootstrap.

**Review by ckadner — APPROVED** [review]
/lgtm

**Pull request merged**
