### PR TITLE
Add readme pages for MAX models

### PR DESCRIPTION
**Pull request by kmh4321**
Signed-off-by: Karthik Muthuraman <karthik.muthuraman@ibm.com>

### CODE REVIEW

**Comment by kmh4321** [comment]
cc: @ckadner @drewbutlerbb4 

closes #39

**Comment by Tomcli** [comment]
@ckadner can you also update the https://github.com/machine-learning-exchange/mlx/blob/main/bootstrapper/catalog_upload.json after merging this PR? The model yaml paths will be changed. Thanks.

**Comment by kmh4321** [comment]
@ckadner got the readmes from the internal repos. 
Check commit #baecd9a.

**Review by ckadner — APPROVED** [review]
/lgtm

Thanks Karthik!

**Pull request merged**
